### PR TITLE
feat: migrate most implementations from base repo

### PR DESCRIPTION
**Pull request by Craksy**
#7 

More or less just copied any files that wouldn't cause an overwrite, and updated `use` statements of various modules accordingly.

Made a few tweaks to `searching::kth_smallest_heap` as it relied on a different version of the `Heap` struct, and made `sorting::quick_sort::partion` public as `searching::kth_smallest` depended on it.

I also took the liberty to rename `string_matching` into just `string` like in the old repo, as there are a few algorithms that aren't strictly related to matching.

This is pretty much my first time contributing to anything. I just came across the issue and thought "move some stuff around? I can do that!" (one of these days I might try my luck contributing some actual code).
Please let me know if there's anything I missed or should've done differently.

### CODE REVIEW

**Comment by alexfertel** [comment]
Hey! Thanks for taking the time to do this! ❤️ 

That's a lot to review hehehe. I wanted to progressively review people's PR to have the time to do it, but I think it's ok this way as well.

I'll take a look in the coming days and will let you know anything that comes up. I'll prioritize the smaller PRs first, though.

Also, I understand I didn't respond in a while, so it is ok if you want to drop this, I can take ownership 👍🏻

**Comment by Craksy** [comment]
> That's a lot to review hehehe. I wanted to progressively review people's PR to have the time to do it, but I think it's ok this way as well.

Yeah, it actually occurred to me just after submitting, and for a moment I was like "where do I un-PR", but I figured it'd probably just get ignored if it was an issue.

I'd love to see it through, I'm just a little hung up at the moment. 

Perhaps it would be more manageable (for both of us) if I rolled back that monster of a commit, and started incrementally reintroducing each algorithm. That way I'll pay a little more attention to each change, and it'll probably be more pleasant for you to review.

Whatever you prefer honestly. Again, I just came across the project and thought I'd try to help out, so I'd like to do it in a way that actually... you know, helpful.

**Comment by alexfertel** [comment]
> Perhaps it would be more manageable (for both of us) if I rolled back that monster of a commit, and started incrementally reintroducing each algorithm. That way I'll pay a little more attention to each change, and it'll probably be more pleasant for you to review.

Yes, I think this is a good idea.

> Whatever you prefer honestly. Again, I just came across the project and thought I'd try to help out, so I'd like to do it in a way that actually... you know, helpful.

I really appreciate it ❤️. You've already been helpful! I'm happy to answer any questions you may have.

I am planning on spending some time in reviews this weekend, so happy to start chipping away at this PR or take a look at a new one.

**Review by alexfertel — APPROVED** [review]
Finally went through most of them! Took me two months lol.

I think it is okay if we merge this, and then just improve docs and everything else.

Thank you for this!

**Pull request merged**
