### PR TITLE
 modified the function to take slices as input and return a vector without the need to create and manipulate additional Vec instances.

### PR DESCRIPTION
**Pull request by abeybernard**

### CODE REVIEW

**Review by alexfertel — APPROVED** [review]
Thanks for contributing! ❤️ 

Looks great! Indeed I think this looks cleaner, more idiomatic and easier to read.

**Comment by alexfertel** [comment]
@abeybernard just noticed a typo in your configured `git` email: `<abeybernard321@gmai.com>`. It's missing the `l` of `gmail`.

**Comment by abeybernard** [comment]
Thank you for noticing the missing l
Was error on my part I'm sorry

**Comment by alexfertel** [comment]
Oh, no worries! Happy to help 👍🏻

**Pull request merged**
