### PR TITLE
refactor(sorting): add traits for sorting algorithms

### PR DESCRIPTION
**Pull request by borghol**
Hi Alex,

Referring to PR #48, I have added two traits:
- Sort
- SortMutable

in an attempt to unify the sorting algorithms behind structs that expose the sort method.

Not sure how complete the feature needs to be, but I believe the PR would be too large at that point to be easily reviewable. I was considering submitting the traits for 1 algorithm at a time, modifying those that do not adhere to the trait properties.

I wanted to get into contributing to OSS, and I thought your library would be a great place to start. Any comments are welcome.

### CODE REVIEW

**Comment by alexfertel** [comment]
Hello @borghol ! Thank you for your contribution!

This is very close to the implementation I was thinking of. However, I need a bit more time to review it and I'm busy with the holidays coming. I'll give it a more in-depth look in the coming days.

**Comment by alexfertel** [comment]
Heyo, @borghol ! 

What is your opinion on the traits from https://github.com/jonhoo/orst/blob/da6ba90195f94ec334f382b07498fc4e01795f20/src/lib.rs ?

I feel like it is fine not to expect algorithms to be stateful, like we have in your implementation, though it might be interesting to understand why the `Ord` type constraint is on `sort` and not on `Sorter`. I also feel like `Sorter` is a better name since it would be the `Sorter` *trait*.  What do you think?

One other thing to consider is that some of the algos don't follow the standard signature. For example, https://github.com/alexfertel/rust-algorithms/blob/87d4d8d27c94ac0d296c99056a651b967096c8e9/src/sorting/shell_sort.rs#L1 

Though it is probably better to address that in a separate PR.

**Comment by borghol** [comment]
As far as adding state to the sorters, I would find it extremely weird for a sorting algorithm to require me to create an instance in order to use. I get that it's less of an issue when it comes to rust, but something like `BubbleSort::sort([1,3,2])`
is much less verbose and much more coherent than `BubbleSort{}.sort([1,3,2])` or `BubbleSort::new().sort([1,3,2])` so I'm with you on that one.

I'm too new to rust to understand the inner workings of placing the constraint on the function vs. on the class, but I assume placing it on the function is generally safer for extending the Sorter trait to do more than just sort. In our case, I don't believe it matters, but I will change it to be on the function for best practices sake.

Sorter does seem like a better name than Sort, I will apply that as well!

As far as the function signatures go, they should be standardized anyways. I can work on standardizing the implementations before completing this PR. Copy will definitely needed to be added on Sorter (but not necessarily MutableSorter) as we are returning a new array anyway. Shell sort seems to have Copy as a constraint but it doesn't seem to need it. There are some additional traits that will also need to be removed as part of standardizing the algorithms.

Lastly, I'm torn between using slices vs using vectors. Any thoughts on this?

**Comment by borghol** [comment]
One last discussion I would like to have, should we make MutableSorter have the function called sort_mut instead of sort?

I know that the function signature is enough. However, as we're making this repo for educational purposes, it would be nice to be able to implement a sort() on the mutable sorters, as it will allow much more flexibility when it comes to programs benchmarking algorithms for example.

**Comment by alexfertel** [comment]
> but I assume placing it on the function is generally safer for extending the Sorter trait to do more than just sort

Yep, that is correct! 👍🏻 

>  I can work on standardizing the implementations before completing this PR

Hmmm, I prefer having it on a separate PR that justifies the change. That is, we make the change that standardizes signatures and tests together. However, I have no strong opinions on the order, so if you are willing to work on that as well, I'm happy to review them and provide support in whatever order you want to do it.

> There are some additional traits that will also need to be removed as part of standardizing the algorithms.

👍🏻 

> Lastly, I'm torn between using slices vs using vectors. Any thoughts on this?

I have several thoughts on this, but to summarize the main ones:

- Slices as parameters make functions more *flexible*. If you think from a callee standpoint, converting from a collection to a slice is usually trivial (using 'usually' for the sake of being careful). However, once you need a `Vec`, a conversion might need to happen.
- `Vec`s are slightly more overhead than slices.
- Sorting can always be reduced to a pure function that takes a collection and returns a new collection sorted whenever the elements of the collection form a partial order (`Sorter` trait). So we don't really need the "variable length" that vectors provide thus a slice makes more sense in the context of sorting.

Hopefully, that helps you choose!

> However, as we're making this repo for educational purposes, it would be nice to be able to implement a sort() on the mutable sorters, as it will allow much more flexibility when it comes to programs benchmarking algorithms for example.

Hmmm, I'm not entirely convinced, because I do agree that the signature should be enough, but I do lean toward what would be best for teaching, so I think it is okay if we rename it. Did you choose `sort_mut` to be consistent with Rust?

---

Btw, I have to say good job! 🚀

**Comment by borghol** [comment]
Hey Alex,

So I have done all the changes that we have agreed on, minus using sort_mut. Looking at the algorithms, it's far more beneficial to understand in-place vs out-of-place sorting, and copying it in the background before sorting just hides that piece of knowledge. 

> Hmmm, I prefer having it on a separate PR that justifies the change. That is, we make the change that standardizes signatures and tests together. However, I have no strong opinions on the order, so if you are willing to work on that as well, I'm happy to review them and provide support in whatever order you want to do it.

How should we approach this change then with regards to the other sorting algorithms? The trait will be incompatible with the majority of these. I suggest taking a modular approach. We can let this PR go through and I will go through the algorithms one at a time, where each PR will implement the trait by standardizing the algorithm's functions and tests alongside it.

**Comment by alexfertel** [comment]
> it's far more beneficial to understand in-place vs out-of-place sorting, and copying it in the background before sorting just hides that piece of knowledge.

Yeah, I agree. 👍🏻 

> We can let this PR go through and I will go through the algorithms one at a time, where each PR will implement the trait by standardizing the algorithm's functions and tests alongside it.

Yeap, that sounds good to me! Feel free to push your changes, I'll take a look and merge 🚀

**Comment by borghol** [comment]
Hey Alex, the agreed changes should all be pushed. Please take a look when you can.

**Review by alexfertel — APPROVED** [review]
LGTM!

**Pull request merged**
